language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get install -y python-tk
  - sudo apt-get install -y python3-tk
install: pip install -r requirements_dev.txt
script: python -m unittest
after_success: coverage run --source=pysankey --omit=pysankey/tests/* -m unittest;coverage html;coveralls
