site_name: "ausankey"

theme:
  name: "mkdocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]

docs_dir: "docs"
site_dir: "_site"
