site_name: "The ausankey package"

nav:
  - Home: index.md
  - User guide: interface.md
  - Examples: examples.md
  - Reference: reference.md
  - Changelog: CHANGELOG.md

theme:
  name: "mkdocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ausankey]
          options:
            docstring_style: numpy

docs_dir: "docs"
site_dir: "_site"
