site_name: "The ausankey package"

nav:
  - Home: index.md
  - Reference: reference.md

theme:
  name: "mkdocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ausankey]
          options:
            docstring_style: google

docs_dir: "docs"
site_dir: "_site"
