
name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10","3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: Test with pytest
      run: hatch run test:test


  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install Hatch
          run: pipx install hatch
        - name: Lint with Ruff
          run: hatch fmt --check



  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install Hatch
          run: pipx install hatch
        - name: Coverage
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cd ${{ vars.SOURCE_DIR }}
            hatch run test:cov
